version: '3'
services:
  file-browser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: '0:0'
    ports:
      - '8091:80'
    volumes:
      - '/home/root/:/srv'
      - '/artifacts/zc0sckk/filebrowser.db:/database.db'
    restart: unless-stopped
    security_opt:
      - 'no-new-privileges:true'
